#!/usr/bin/env python 
"""
@author: Hesham ElAbd
@brief: write the results generated by the library
@version: 0.0.1
"""
import numpy as np 
import h5py
from IPTK.DataStructure.Experiment import Experiment
from IPTK.DataStructure.Peptide import Peptide
from typing import List
import pandas as pd
# define some types 
Peptides= List[Peptide]
Names= List[str]

def write_mapped_tensor_to_h5py(tensor: np.ndarray, path2write: str, dataSet_name: str ='MAPPED_TENSOR')->None:
    """
    @brief: write a mapped tensor to an hdf5 file 
    @param: tensor: The provided tensor to write the result to 
    @param: path2Write: The path of the output file 
    @param: dataSet_name: The name of the dataset inside the mapped tensor 
    """
    try:
        file_handler=h5py.File(path2write,'w')
    except Exception as exp:
        raise IOError(f'While opening the file: {path2write} for writing, the following error was encountered: {exp}')
    # create the dataset 
    file_handler.create_dataset(dataSet_name,data=tensor)
    # flush the data 
    file_handler.close()
    return 

def write_annotated_sequences(peptides: List[str], labels: List[int], path2write: str,
                            sep: str = ',', shuffle: bool =True) ->None:
    """
    @brief: take a list of peptides along with it sequences and write the results to a CSV file.
    @param: peptides: a list of peptide sequences 
    @param: labels: a list of numerical labels associated with the peptides 
    @param: path2write: the path to write the generated file 
    @param: sep: the separator in the resulting table, default is comma  
    @param: shuffle: whether or not to shuffle the table 
    """
    if len(peptides) != len(labels):
        raise ValueError(f'The provided lists do not match, peptides have: {len(peptides)} elements while labels have: {len(peptides)} elements')
    # define the dataframe results 
    table: pd.DataFrame = pd.DataFrame({
        'peptides':peptides,
        'labels': labels
    }) 
    # shuffle the database 
    if shuffle:
        table=table.sample(frac=1.0)
    # write the results 
    try: 
        table.to_csv(path2write,sep=sep, index=False, header=True)
    except Exception as exp: 
        raise IOError(f'While writing the results table, the following error was encountered: {exp}')
    

def write_named_peptides_to_fasta(names: Names, peptides: Peptides, output_file:str):
    """
    @brief: takes a list of names and peptide sequences and writes them as an output file to the disk as fasta files
    @param: names: a list of sequences names 
    @param: seq: a list of peptide sequences 
    @param: output_file: the name of the output file to write the results to, it will OVERWRITE existing files
    """
    if len(names) != len (peptides): 
        raise ValueError(f"The length of the names container: {len(names)} does not equal the length of the sequences container: {len(peptides)}")
    # write the files 
    try:
        with open(output_file, 'w') as writer:
            for idx in range(len(names)): 
                writer.write('>'+names[idx]+'\n')
                writer.write(peptides[idx]+'\n')
    except Exception as exp: 
        raise RuntimeError(f'While writing the output file the following error was encountered: {exp}') 

def write_auto_named_peptide_to_fasta(peptides:Peptides, output_file:str ):
    """
    @brief: takes a list of peptides, generate automatic names for the pepetides and write the results to the disk as fasta files 
    @param: peptides: a list of peptide sequences 
    @param: output_file: the name of the output file to write the results to, it will OVERWRITE existing files
    """
    # generate automatic names for the pepetide 
    names=['PEP_AUTO_NAME_'+str(idx) for idx in range(len(peptides))]
    # call the writer functions 
    write_named_peptides_to_fasta(names, peptides,output_file)
    
def write_pep_file(peptides:Peptides, output_file:str):
    """
    @brief: takes a file and write the peptides to .pep file which is a text file that contain one peptide per line
    @param: peptides: a list of peptide sequences 
    @param: output_file: the name of the output file to write the results to, it will OVERWRITE existing files
    """
    try: 
        with open(output_file,'w') as writer: 
            for pep in peptides: 
                writer.write(pep+'\n')
    except Exception as exp: 
        raise RuntimeError(f'While writing the file, the following error was encountered: {exp}')
    